# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layerPaintUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1046, 682)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400, 0))
        MainWindow.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"background-color:#efefef;\n"
"color:#000;\n"
"")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(500, 0))
        self.frame.setStyleSheet("")
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem, 0, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 0, 2, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 1, 2, 2, 1)
        self.mainGridLayout = QtWidgets.QGridLayout()
        self.mainGridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.mainGridLayout.setContentsMargins(5, 6, 7, 7)
        self.mainGridLayout.setVerticalSpacing(7)
        self.mainGridLayout.setObjectName("mainGridLayout")
        self.label2 = QtWidgets.QLabel(self.frame)
        self.label2.setMinimumSize(QtCore.QSize(40, 30))
        self.label2.setMaximumSize(QtCore.QSize(80, 30))
        self.label2.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 0px solid #000")
        self.label2.setObjectName("label2")
        self.mainGridLayout.addWidget(self.label2, 1, 1, 1, 1)
        self.y1LineColorPushButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y1LineColorPushButton.sizePolicy().hasHeightForWidth())
        self.y1LineColorPushButton.setSizePolicy(sizePolicy)
        self.y1LineColorPushButton.setMinimumSize(QtCore.QSize(120, 30))
        self.y1LineColorPushButton.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 1px solid #000")
        self.y1LineColorPushButton.setObjectName("y1LineColorPushButton")
        self.mainGridLayout.addWidget(self.y1LineColorPushButton, 5, 5, 1, 1)
        self.y1TitleTextEdit = QtWidgets.QTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y1TitleTextEdit.sizePolicy().hasHeightForWidth())
        self.y1TitleTextEdit.setSizePolicy(sizePolicy)
        self.y1TitleTextEdit.setMinimumSize(QtCore.QSize(130, 30))
        self.y1TitleTextEdit.setMaximumSize(QtCore.QSize(130, 30))
        self.y1TitleTextEdit.setBaseSize(QtCore.QSize(40, 0))
        self.y1TitleTextEdit.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 1px solid #000")
        self.y1TitleTextEdit.setObjectName("y1TitleTextEdit")
        self.mainGridLayout.addWidget(self.y1TitleTextEdit, 5, 2, 1, 1)
        self.savePushButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savePushButton.sizePolicy().hasHeightForWidth())
        self.savePushButton.setSizePolicy(sizePolicy)
        self.savePushButton.setMinimumSize(QtCore.QSize(40, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.savePushButton.setFont(font)
        self.savePushButton.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 1px solid #000")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/18637/.designer/uisource/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.savePushButton.setIcon(icon)
        self.savePushButton.setIconSize(QtCore.QSize(0, 0))
        self.savePushButton.setCheckable(False)
        self.savePushButton.setAutoExclusive(False)
        self.savePushButton.setAutoDefault(False)
        self.savePushButton.setObjectName("savePushButton")
        self.mainGridLayout.addWidget(self.savePushButton, 0, 2, 1, 1)
        self.widthLineEdit = QtWidgets.QLineEdit(self.frame)
        self.widthLineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.widthLineEdit.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 1px solid #000")
        self.widthLineEdit.setObjectName("widthLineEdit")
        self.mainGridLayout.addWidget(self.widthLineEdit, 2, 1, 1, 1)
        self.y1LineTypeComboBox = QtWidgets.QComboBox(self.frame)
        self.y1LineTypeComboBox.setMinimumSize(QtCore.QSize(40, 30))
        self.y1LineTypeComboBox.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 1px solid #000")
        self.y1LineTypeComboBox.setObjectName("y1LineTypeComboBox")
        self.y1LineTypeComboBox.addItem("")
        self.y1LineTypeComboBox.addItem("")
        self.y1LineTypeComboBox.addItem("")
        self.y1LineTypeComboBox.addItem("")
        self.y1LineTypeComboBox.addItem("")
        self.y1LineTypeComboBox.addItem("")
        self.mainGridLayout.addWidget(self.y1LineTypeComboBox, 5, 3, 1, 1)
        self.dpitLineEdit = QtWidgets.QLineEdit(self.frame)
        self.dpitLineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.dpitLineEdit.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 1px solid #000")
        self.dpitLineEdit.setObjectName("dpitLineEdit")
        self.mainGridLayout.addWidget(self.dpitLineEdit, 2, 3, 1, 1)
        self.lineWidthLabel = QtWidgets.QLabel(self.frame)
        self.lineWidthLabel.setMinimumSize(QtCore.QSize(80, 30))
        self.lineWidthLabel.setMaximumSize(QtCore.QSize(80, 30))
        self.lineWidthLabel.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 0px solid #000")
        self.lineWidthLabel.setObjectName("lineWidthLabel")
        self.mainGridLayout.addWidget(self.lineWidthLabel, 4, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 0px solid #000")
        self.label.setObjectName("label")
        self.mainGridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.XTitleTextEdit = QtWidgets.QTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XTitleTextEdit.sizePolicy().hasHeightForWidth())
        self.XTitleTextEdit.setSizePolicy(sizePolicy)
        self.XTitleTextEdit.setMinimumSize(QtCore.QSize(130, 30))
        self.XTitleTextEdit.setMaximumSize(QtCore.QSize(130, 30))
        self.XTitleTextEdit.setBaseSize(QtCore.QSize(40, 0))
        self.XTitleTextEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.XTitleTextEdit.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 1px solid #000")
        self.XTitleTextEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.XTitleTextEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.XTitleTextEdit.setLineWidth(0)
        self.XTitleTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.XTitleTextEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.XTitleTextEdit.setTabStopWidth(80)
        self.XTitleTextEdit.setTabStopDistance(80.0)
        self.XTitleTextEdit.setObjectName("XTitleTextEdit")
        self.mainGridLayout.addWidget(self.XTitleTextEdit, 4, 2, 1, 1)
        self.y1LineWidthDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y1LineWidthDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.y1LineWidthDoubleSpinBox.setSizePolicy(sizePolicy)
        self.y1LineWidthDoubleSpinBox.setMinimumSize(QtCore.QSize(40, 30))
        self.y1LineWidthDoubleSpinBox.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 1px solid #000")
        self.y1LineWidthDoubleSpinBox.setObjectName("y1LineWidthDoubleSpinBox")
        self.mainGridLayout.addWidget(self.y1LineWidthDoubleSpinBox, 5, 4, 1, 1)
        self.y1Label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y1Label.sizePolicy().hasHeightForWidth())
        self.y1Label.setSizePolicy(sizePolicy)
        self.y1Label.setMinimumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.y1Label.setFont(font)
        self.y1Label.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 0px solid #000")
        self.y1Label.setObjectName("y1Label")
        self.mainGridLayout.addWidget(self.y1Label, 5, 0, 1, 1)
        self.label4 = QtWidgets.QLabel(self.frame)
        self.label4.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 0px solid #000")
        self.label4.setObjectName("label4")
        self.mainGridLayout.addWidget(self.label4, 1, 3, 1, 1)
        self.xLabel = QtWidgets.QLabel(self.frame)
        self.xLabel.setMinimumSize(QtCore.QSize(40, 30))
        self.xLabel.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.xLabel.setFont(font)
        self.xLabel.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 0px solid #000")
        self.xLabel.setObjectName("xLabel")
        self.mainGridLayout.addWidget(self.xLabel, 4, 0, 1, 1)
        self.y1ComboBox = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y1ComboBox.sizePolicy().hasHeightForWidth())
        self.y1ComboBox.setSizePolicy(sizePolicy)
        self.y1ComboBox.setMinimumSize(QtCore.QSize(120, 30))
        self.y1ComboBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.y1ComboBox.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 1px solid #000")
        self.y1ComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.y1ComboBox.setMinimumContentsLength(10)
        self.y1ComboBox.setObjectName("y1ComboBox")
        self.y1ComboBox.addItem("")
        self.mainGridLayout.addWidget(self.y1ComboBox, 5, 1, 1, 1)
        self.label3 = QtWidgets.QLabel(self.frame)
        self.label3.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 0px solid #000")
        self.label3.setObjectName("label3")
        self.mainGridLayout.addWidget(self.label3, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.mainGridLayout.addWidget(self.label_6, 1, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setMinimumSize(QtCore.QSize(40, 30))
        self.label_8.setMaximumSize(QtCore.QSize(80, 30))
        self.label_8.setObjectName("label_8")
        self.mainGridLayout.addWidget(self.label_8, 4, 3, 1, 1)
        self.addYpushButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addYpushButton.sizePolicy().hasHeightForWidth())
        self.addYpushButton.setSizePolicy(sizePolicy)
        self.addYpushButton.setMinimumSize(QtCore.QSize(60, 30))
        self.addYpushButton.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 1px solid #000")
        self.addYpushButton.setObjectName("addYpushButton")
        self.mainGridLayout.addWidget(self.addYpushButton, 6, 0, 1, 1)
        self.XComboBox = QtWidgets.QComboBox(self.frame)
        self.XComboBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XComboBox.sizePolicy().hasHeightForWidth())
        self.XComboBox.setSizePolicy(sizePolicy)
        self.XComboBox.setMinimumSize(QtCore.QSize(120, 30))
        self.XComboBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.XComboBox.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 1px solid #000")
        self.XComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.XComboBox.setObjectName("XComboBox")
        self.XComboBox.addItem("")
        self.mainGridLayout.addWidget(self.XComboBox, 4, 1, 1, 1)
        self.heightLineEdit = QtWidgets.QLineEdit(self.frame)
        self.heightLineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.heightLineEdit.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 1px solid #000")
        self.heightLineEdit.setObjectName("heightLineEdit")
        self.mainGridLayout.addWidget(self.heightLineEdit, 2, 2, 1, 1)
        self.previewPushButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewPushButton.sizePolicy().hasHeightForWidth())
        self.previewPushButton.setSizePolicy(sizePolicy)
        self.previewPushButton.setMinimumSize(QtCore.QSize(25, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.previewPushButton.setFont(font)
        self.previewPushButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.previewPushButton.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 1px solid #000")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/18637/.designer/uisource/preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previewPushButton.setIcon(icon1)
        self.previewPushButton.setIconSize(QtCore.QSize(0, 0))
        self.previewPushButton.setAutoDefault(False)
        self.previewPushButton.setDefault(False)
        self.previewPushButton.setFlat(True)
        self.previewPushButton.setObjectName("previewPushButton")
        self.mainGridLayout.addWidget(self.previewPushButton, 0, 1, 1, 1)
        self.pictureNameLineEdit = QtWidgets.QLineEdit(self.frame)
        self.pictureNameLineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.pictureNameLineEdit.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 1px solid #000")
        self.pictureNameLineEdit.setObjectName("pictureNameLineEdit")
        self.mainGridLayout.addWidget(self.pictureNameLineEdit, 2, 4, 1, 1)
        self.selectFileButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectFileButton.sizePolicy().hasHeightForWidth())
        self.selectFileButton.setSizePolicy(sizePolicy)
        self.selectFileButton.setMinimumSize(QtCore.QSize(60, 50))
        self.selectFileButton.setSizeIncrement(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.selectFileButton.setFont(font)
        self.selectFileButton.setAcceptDrops(False)
        self.selectFileButton.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 1px solid #000")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/18637/.designer/uisource/importData.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.selectFileButton.setIcon(icon2)
        self.selectFileButton.setIconSize(QtCore.QSize(0, 0))
        self.selectFileButton.setAutoDefault(False)
        self.selectFileButton.setDefault(True)
        self.selectFileButton.setFlat(False)
        self.selectFileButton.setObjectName("selectFileButton")
        self.mainGridLayout.addWidget(self.selectFileButton, 0, 0, 1, 1)
        self.deleteYPushButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteYPushButton.sizePolicy().hasHeightForWidth())
        self.deleteYPushButton.setSizePolicy(sizePolicy)
        self.deleteYPushButton.setMinimumSize(QtCore.QSize(60, 30))
        self.deleteYPushButton.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 1px solid #000")
        self.deleteYPushButton.setObjectName("deleteYPushButton")
        self.mainGridLayout.addWidget(self.deleteYPushButton, 7, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setMinimumSize(QtCore.QSize(40, 30))
        self.label_4.setMaximumSize(QtCore.QSize(80, 30))
        self.label_4.setObjectName("label_4")
        self.mainGridLayout.addWidget(self.label_4, 2, 6, 1, 1)
        self.MaxXLineEdit = QtWidgets.QLineEdit(self.frame)
        self.MaxXLineEdit.setMinimumSize(QtCore.QSize(40, 30))
        self.MaxXLineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.MaxXLineEdit.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 1px solid #000")
        self.MaxXLineEdit.setObjectName("MaxXLineEdit")
        self.mainGridLayout.addWidget(self.MaxXLineEdit, 4, 6, 1, 1)
        self.y1MaxYLineEdit = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y1MaxYLineEdit.sizePolicy().hasHeightForWidth())
        self.y1MaxYLineEdit.setSizePolicy(sizePolicy)
        self.y1MaxYLineEdit.setMinimumSize(QtCore.QSize(40, 30))
        self.y1MaxYLineEdit.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 1px solid #000")
        self.y1MaxYLineEdit.setObjectName("y1MaxYLineEdit")
        self.mainGridLayout.addWidget(self.y1MaxYLineEdit, 5, 6, 1, 1)
        self.MinXLineEdit = QtWidgets.QLineEdit(self.frame)
        self.MinXLineEdit.setMinimumSize(QtCore.QSize(40, 30))
        self.MinXLineEdit.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 1px solid #000")
        self.MinXLineEdit.setObjectName("MinXLineEdit")
        self.mainGridLayout.addWidget(self.MinXLineEdit, 4, 7, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setMinimumSize(QtCore.QSize(40, 30))
        self.label_5.setMaximumSize(QtCore.QSize(80, 30))
        self.label_5.setObjectName("label_5")
        self.mainGridLayout.addWidget(self.label_5, 2, 7, 1, 1)
        self.y1MinYLineEdit = QtWidgets.QLineEdit(self.frame)
        self.y1MinYLineEdit.setMinimumSize(QtCore.QSize(40, 30))
        self.y1MinYLineEdit.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 1px solid #000")
        self.y1MinYLineEdit.setObjectName("y1MinYLineEdit")
        self.mainGridLayout.addWidget(self.y1MinYLineEdit, 5, 7, 1, 1)
        self.XStepLineEdit = QtWidgets.QLineEdit(self.frame)
        self.XStepLineEdit.setMinimumSize(QtCore.QSize(40, 30))
        self.XStepLineEdit.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 1px solid #000")
        self.XStepLineEdit.setObjectName("XStepLineEdit")
        self.mainGridLayout.addWidget(self.XStepLineEdit, 4, 8, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setMinimumSize(QtCore.QSize(40, 30))
        self.label_7.setMaximumSize(QtCore.QSize(80, 30))
        self.label_7.setObjectName("label_7")
        self.mainGridLayout.addWidget(self.label_7, 2, 8, 1, 1)
        self.y1StepLineEdit = QtWidgets.QLineEdit(self.frame)
        self.y1StepLineEdit.setMinimumSize(QtCore.QSize(40, 30))
        self.y1StepLineEdit.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:5px;\n"
"color:#000;\n"
"border: 1px solid #000")
        self.y1StepLineEdit.setObjectName("y1StepLineEdit")
        self.mainGridLayout.addWidget(self.y1StepLineEdit, 5, 8, 1, 1)
        self.gridLayout_4.addLayout(self.mainGridLayout, 2, 1, 2, 1)
        self.dataTableWidget = QtWidgets.QTableWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataTableWidget.sizePolicy().hasHeightForWidth())
        self.dataTableWidget.setSizePolicy(sizePolicy)
        self.dataTableWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.dataTableWidget.setStyleSheet("font: 75 14pt \"Adobe Arabic\";\n"
"border-radius:0px;\n"
"color:#000;\n"
"border: 1px solid #000;\n"
"background-color:#FFF")
        self.dataTableWidget.setGridStyle(QtCore.Qt.CustomDashLine)
        self.dataTableWidget.setObjectName("dataTableWidget")
        self.dataTableWidget.setColumnCount(0)
        self.dataTableWidget.setRowCount(0)
        self.dataTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.gridLayout_4.addWidget(self.dataTableWidget, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1046, 25))
        self.menubar.setObjectName("menubar")
        self.menulayerPaint = QtWidgets.QMenu(self.menubar)
        self.menulayerPaint.setObjectName("menulayerPaint")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menulayerPaint.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "layerPaintUtil"))
        self.label2.setText(_translate("MainWindow", "宽"))
        self.y1LineColorPushButton.setText(_translate("MainWindow", "连线颜色"))
        self.y1TitleTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Adobe Arabic\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">y轴标题</p></body></html>"))
        self.savePushButton.setText(_translate("MainWindow", "保 存"))
        self.widthLineEdit.setText(_translate("MainWindow", "1920"))
        self.y1LineTypeComboBox.setItemText(0, _translate("MainWindow", "线型"))
        self.y1LineTypeComboBox.setItemText(1, _translate("MainWindow", "实线 -"))
        self.y1LineTypeComboBox.setItemText(2, _translate("MainWindow", "点虚线 :"))
        self.y1LineTypeComboBox.setItemText(3, _translate("MainWindow", "破折线 --"))
        self.y1LineTypeComboBox.setItemText(4, _translate("MainWindow", "点划线 -."))
        self.y1LineTypeComboBox.setItemText(5, _translate("MainWindow", "不画线 "))
        self.dpitLineEdit.setText(_translate("MainWindow", "120"))
        self.lineWidthLabel.setText(_translate("MainWindow", "线 宽"))
        self.label.setText(_translate("MainWindow", "图片尺寸："))
        self.XTitleTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Adobe Arabic\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">x轴标题</p></body></html>"))
        self.y1LineWidthDoubleSpinBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>线宽</p></body></html>"))
        self.y1Label.setText(_translate("MainWindow", "y轴"))
        self.label4.setText(_translate("MainWindow", "DPI"))
        self.xLabel.setText(_translate("MainWindow", "x轴"))
        self.y1ComboBox.setItemText(0, _translate("MainWindow", "y轴"))
        self.label3.setText(_translate("MainWindow", "高"))
        self.label_6.setText(_translate("MainWindow", "图片名称"))
        self.label_8.setText(_translate("MainWindow", "线 型"))
        self.addYpushButton.setText(_translate("MainWindow", "+Y"))
        self.XComboBox.setItemText(0, _translate("MainWindow", "x轴"))
        self.heightLineEdit.setText(_translate("MainWindow", "1080"))
        self.previewPushButton.setText(_translate("MainWindow", "预 览"))
        self.pictureNameLineEdit.setText(_translate("MainWindow", "图片名称"))
        self.selectFileButton.setText(_translate("MainWindow", "导入数据"))
        self.deleteYPushButton.setText(_translate("MainWindow", "-Y"))
        self.label_4.setText(_translate("MainWindow", "最大值"))
        self.MaxXLineEdit.setText(_translate("MainWindow", "最大值"))
        self.y1MaxYLineEdit.setText(_translate("MainWindow", "最大值"))
        self.MinXLineEdit.setText(_translate("MainWindow", "最小值"))
        self.label_5.setText(_translate("MainWindow", "最小值"))
        self.y1MinYLineEdit.setText(_translate("MainWindow", "最小值"))
        self.XStepLineEdit.setText(_translate("MainWindow", "步长"))
        self.label_7.setText(_translate("MainWindow", "步长"))
        self.y1StepLineEdit.setText(_translate("MainWindow", "步长"))
        self.menulayerPaint.setTitle(_translate("MainWindow", "绘图工具"))
